global:
  scrape_interval: 15s
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
  
  - job_name: "shorten-service"
    static_configs:
      - targets: ["shorten-service:8000"]
    
  - job_name: "redirect_service"
    static_configs:
      - targets: ["redirect_service:8001"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  
  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra-exporter:8080"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
